name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: dockercourse.azurecr.io
        username: dockercourse
        password: BYUNydBGpIx1DOqcykIe4LhTfiHPduEwf7rDhDaf37+ACRC3qI7v
    - run: |
        docker build . -t dockercourse.azurecr.io/myapp:${{ github.sha }}
        docker push dockercourse.azurecr.io/myapp:${{ github.sha }}